[build]
  base = ""
  publish = "dist/"
  command = "npm run build"
  functions = 'functions'
  

[dev]
  framework = "astro"
  base = ""
  publish = "dist/"
  command = "npm run dev"
  functions = 'functions'

  [functions]
    [functions.createWordleHint]
    timeout = 30 # Set the timeout to 30 seconds